### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by bpaauwe** [bpaauwe/WFNodeServer#13]
Add some type of logging capability with various levels.  The log should be output to the web interface and possibly also saved.

May be helpful for debugging issues.

**Comment by bpaauwe** [comment]
Started working on logging facility. 

Created basic logging class.

**Comment by bpaauwe** [comment]
Does the log information need to be dynamically updated in the browser?  If so, does this mean the node server needs to run some javascript on the browser to make a websocket connection back to the node server?

Or is setting up a refresh timer to have have the log page refresh periodically OK?

**Comment by GaryFunk** [comment]
Oh. A websocket to the browser. Interesting.  I like that idea if it doesn't eat up resources

**Comment by bpaauwe** [comment]
Pushed. 

This version updates the browser based log at 2 second intervals.  It seems like a reasonable approach. 

The log is accessible using "/log" for the URL.
