### ISSUE TITLE
Sensor Status

### ISSUE THREAD

**Issue by GaryFunk** [bpaauwe/WFNodeServer#26]
Consider changing from Failed to Triggered on these states as Failed gives an incorrect impression to the user.

0x00000002 | AIR | lightning noise
0x00000004 | AIR | lightning disturber

**Comment by bpaauwe** [comment]
Added a new editor that sets the status of lightning noise and disturber to OK and Triggered.

**Comment by GaryFunk** [comment]
In the Hub firmware a Sensor status for Failed either means the sensor is bad or the voltage in the device has dropped too low to provide adequate power the sensor.

I suggest to count the number of consecutive "fails" and if it reaches X then marked it as "Failed" otherwise mark it as "Triggered."  I feel it is entirely possible to have a sensor trigger one time and then be clear for the next 100 times.

**Comment by bpaauwe** [comment]
Any idea what a good value for X is? 2, 5, more?

And I'm assuming this doesn't apply to the lightning disturber or noise.

**Comment by GaryFunk** [comment]
Start with 3 and see what happens. I've never seen any Sensor set other than Lightning Disturber. 

Correct.  It would not apply to disturber or noise. 

The others would go from OK to Triggered to Failed.

**Comment by GaryFunk** [comment]
I would use:

0 = Normal
1 = Triggered
2 = Failed

Or stay with 0 = OK. I prefer Normal because I just don't like to use OK.

**Comment by bpaauwe** [comment]
I created a new issue (#32) to cover tri-stating the sensor status display.
