### ISSUE TITLE
Use single unit for uptime value 

### ISSUE THREAD

**Issue by bpaauwe** [bpaauwe/WFNodeServer#29]
It's kind of cool that the uptime can switch between seconds/minutes/hours/days as the uptime increases but this makes it useless for any type of conditional monitoring.

Probably best to just change this to days (or fractions of days).

**Comment by GaryFunk** [comment]
I agree. Could it be in a days.hours format?
6.13  would be 6 days 13 hours. I don't see anything that will allow 6.13.45 but that would be nice.
