### ISSUE TITLE
Wind_direction_degrees may not be correct UOM for wind direction

### ISSUE THREAD

**Issue by bpaauwe** [bpaauwe/WFNodeServer#33]
The ISY's WIND_DIRECTION_DEGREES UOM seems to be specific to match what a weather service is reporting for wind direction.  In most cases it displays the correct numeric direction, however for the four major compass points, it displays the direction as text (North, South, East, West) and if the direction is zero, it assumes that means no wind and displays "No Wind".  In our case a direction of 0 means just that, zero degrees or North.

A better choice for this value is probably the generic degree UOM.

**Comment by GaryFunk** [comment]
Please remember to update the version.txt to version 1.0.0.10
